force-app/main/default/objects/FixerCredentials__c/FixerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Fixer credentials</label>
</CustomObject>

force-app/main/default/objects/FixerCredentials__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access token</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixerCredentials__c/fields/BaseUrl__c.field-meta.xml
<CustomField>
    <fullName>BaseUrl__c</fullName>
    <label>Base URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/DateBooked__c.field-meta.xml
<CustomField>
    <fullName>DateBooked__c</fullName>
    <label>Date Booked</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellAmount__c.field-meta.xml
<CustomField>
    <fullName>SellAmount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <label>EUR (European euro)</label>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
        <label>USD (U.S. Dollar)</label>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
        <label>GBP (British Pound)</label>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
        <label>AUD (Australian Dollar)</label>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
        <label>CAD (Canadian Dollar)</label>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
        <label>CHF (Swiss Franc)</label>
    </customValue>
    <customValue>
        <fullName>CNY</fullName>
        <label>CNY (Chinese yuan)</label>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
        <label>JPY (Japanese yen)</label>
    </customValue>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Other/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    public static FixerCredentials__c createFixerCredentials() {
        FixerCredentials__c testCredentials = new FixerCredentials__c(
            AccessToken__c = 'MOCKDATA',
            BaseUrl__c     = 'http://data.fixer.io/api/',
            Name           = 'Production'
        );
        insert testCredentials;
        return testCredentials;
    }

    public static Trade__c createNewTrade() {
        Trade__c newTrade = new Trade__c(
            BuyAmount__c = 1,
            BuyCurrency__c = 'USD',
            DateBooked__c = datetime.now(),
            SellAmount__c = 1,
            SellCurrency__c = 'EUR',
            Rate__c = 1
        );
        insert newTrade;
        return newTrade;
    }

    public static Group fillTradeReviewersQueue() {

        // As we will run test with SeeAllData=true we don't have to create Queue
        Group Queue = [SELECT Id FROM Group WHERE type='Queue' AND Name=:'Trade reviewers' LIMIT 1];

        List<User> newUsers = createUsers(3);

        List<GroupMember> groupMembers = new List<GroupMember>();
        groupMembers.add(new GroupMember(UserOrGroupId = newUsers[0].Id, GroupId = Queue.Id));
        groupMembers.add(new GroupMember(UserOrGroupId = newUsers[1].Id, GroupId = Queue.Id));
        groupMembers.add(new GroupMember(UserOrGroupId = newUsers[2].Id, GroupId = Queue.Id));

        insert groupMembers;
        return Queue;
    }

    private static List<User> createUsers(Decimal usersNumber) {
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        String orgId = UserInfo.getOrganizationId();
        List<User> usersToCreate = new List<User>();
        for (Decimal i = 0; i < usersNumber; i++) {
            User newUser = new User(
                FirstName='Test',
                LastName='Test',
                Alias = 'tst',
                Email = 'test@test.invalid',
                Username = 'test@test.' + orgId + '.invalid' + i,
                ProfileId = profileId.id,
                TimeZoneSidKey = 'GMT',
                LanguageLocaleKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LocaleSidKey = 'en_US'
            );
            usersToCreate.add(newUser);
        }
        insert usersToCreate;
        return usersToCreate;
    }
}