force-app/main/default/objects/FixerCredentials__c/FixerCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Fixer credentials</label>
</CustomObject>

force-app/main/default/objects/FixerCredentials__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access token</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixerCredentials__c/fields/BaseUrl__c.field-meta.xml
<CustomField>
    <fullName>BaseUrl__c</fullName>
    <label>Base URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Other/FixerService.cls
public with sharing class FixerService {
    private static FixerCredentials__c getToken() {
        return FixerCredentials__c.getValues('Production');
    }

    private static string makeCallout(string Url) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(Url);
        request.setMethod('GET');
        HttpResponse jsonResponse = http.send(request);
        if(jsonResponse.getStatusCode() == 200) {
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(jsonResponse.getBody());
            Boolean success = (Boolean) results.get('success');
            if (!success) {
                Map<String, Object> error = (Map<String, Object>) results.get('error');
                string errorInfo = (string) error.get('info');
                string errorType = (string) error.get('type');
                if (errorType == 'base_currency_access_restricted') {
                    throw new AuraHandledException(System.Label.ApiTokenRestriction);
                }
                throw new AuraHandledException(System.Label.ApiWrongResponse + '\n' + errorInfo);
            }
            return jsonResponse.getBody();
        } else {
            throw new AuraHandledException(System.Label.ApiResponseError);
        }
    }

    @AuraEnabled(cacheable=false)
    public static string getRate(string buyCurrency, string sellCurrency) {
        FixerCredentials__c AuthToken = GetToken();
        string url = AuthToken.BaseUrl__c + 'latest';
        url += '?access_key='   + AuthToken.AccessToken__c;
        url += '&base='         + sellCurrency;
        url += '&symbols='      + buyCurrency;

        return MakeCallout(url);
    }
}